// Employee Accounts Data
export const accounts = [
  {
    id: 1,
    account_name: "Ahmad Wijaya",
    account_jenis_kelamin: "Laki-laki",
    account_tanggal_lahir: "1985-03-15",
    account_unit: "Inspektorat Utama",
    account_jabatan: "Auditor Ahli Utama",
    account_pangkat: "Pembina Utama Muda",
    account_golongan: "IV/c",
  },
  {
    id: 2,
    account_name: "Siti Nurhaliza",
    account_jenis_kelamin: "Perempuan",
    account_tanggal_lahir: "1988-07-22",
    account_unit: "Inspektorat Wilayah I",
    account_jabatan: "Auditor Ahli Madya",
    account_pangkat: "Pembina Tingkat I",
    account_golongan: "IV/b",
  },
  {
    id: 3,
    account_name: "Budi Santoso",
    account_jenis_kelamin: "Laki-laki",
    account_tanggal_lahir: "1990-11-08",
    account_unit: "Inspektorat Wilayah II",
    account_jabatan: "Auditor Ahli Muda",
    account_pangkat: "Pembina",
    account_golongan: "IV/a",
  },
  {
    id: 4,
    account_name: "Dewi Sartika",
    account_jenis_kelamin: "Perempuan",
    account_tanggal_lahir: "1987-05-12",
    account_unit: "Inspektorat Wilayah III",
    account_jabatan: "Auditor Ahli Pertama",
    account_pangkat: "Penata Tingkat I",
    account_golongan: "III/d",
  },
  {
    id: 5,
    account_name: "Eko Prasetyo",
    account_jenis_kelamin: "Laki-laki",
    account_tanggal_lahir: "1992-09-30",
    account_unit: "Inspektorat Wilayah IV",
    account_jabatan: "Auditor Terampil",
    account_pangkat: "Penata Muda Tingkat I",
    account_golongan: "III/b",
  },
  {
    id: 6,
    account_name: "Fitri Handayani",
    account_jenis_kelamin: "Perempuan",
    account_tanggal_lahir: "1989-12-18",
    account_unit: "Inspektorat Utama",
    account_jabatan: "Auditor Ahli Muda",
    account_pangkat: "Pembina",
    account_golongan: "IV/a",
  },
  {
    id: 7,
    account_name: "Hendra Gunawan",
    account_jenis_kelamin: "Laki-laki",
    account_tanggal_lahir: "1986-02-25",
    account_unit: "Inspektorat Wilayah I",
    account_jabatan: "Auditor Ahli Madya",
    account_pangkat: "Pembina Tingkat I",
    account_golongan: "IV/b",
  },
  {
    id: 8,
    account_name: "Indira Sari",
    account_jenis_kelamin: "Perempuan",
    account_tanggal_lahir: "1991-06-14",
    account_unit: "Inspektorat Wilayah II",
    account_jabatan: "Auditor Ahli Pertama",
    account_pangkat: "Penata Tingkat I",
    account_golongan: "III/d",
  },
  {
    id: 9,
    account_name: "Joko Widodo",
    account_jenis_kelamin: "Laki-laki",
    account_tanggal_lahir: "1984-10-05",
    account_unit: "Inspektorat Wilayah III",
    account_jabatan: "Auditor Ahli Utama",
    account_pangkat: "Pembina Utama Muda",
    account_golongan: "IV/c",
  },
  {
    id: 10,
    account_name: "Kartika Dewi",
    account_jenis_kelamin: "Perempuan",
    account_tanggal_lahir: "1993-04-20",
    account_unit: "Inspektorat Wilayah IV",
    account_jabatan: "Auditor Terampil",
    account_pangkat: "Penata Muda",
    account_golongan: "III/a",
  },
]

// Family Data
export const families = [
  {
    id: 1,
    account_id: 1,
    family_name: "Sari Wijaya",
    family_hubungan: "Istri",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "1987-08-20",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Jakarta Selatan",
  },
  {
    id: 2,
    account_id: 1,
    family_name: "Andi Wijaya",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "2010-12-15",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Jakarta Selatan",
  },
  {
    id: 3,
    account_id: 1,
    family_name: "Maya Wijaya",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "2013-05-08",
    kondisi_kesehatan: "Sakit",
    domisili_sekarang: "Jakarta Selatan",
  },
  {
    id: 4,
    account_id: 2,
    family_name: "Rahmat Hidayat",
    family_hubungan: "Suami",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "1985-11-12",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Bandung",
  },
  {
    id: 5,
    account_id: 2,
    family_name: "Zahra Hidayat",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "2012-03-25",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Bandung",
  },
  {
    id: 6,
    account_id: 3,
    family_name: "Rina Santoso",
    family_hubungan: "Istri",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "1992-07-18",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Surabaya",
  },
  {
    id: 7,
    account_id: 3,
    family_name: "Dika Santoso",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "2015-09-10",
    kondisi_kesehatan: "Sakit",
    domisili_sekarang: "Surabaya",
  },
  {
    id: 8,
    account_id: 4,
    family_name: "Agus Prasetyo",
    family_hubungan: "Suami",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "1984-01-30",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Medan",
  },
  {
    id: 9,
    account_id: 4,
    family_name: "Lila Prasetyo",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "2011-06-22",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Medan",
  },
  {
    id: 10,
    account_id: 4,
    family_name: "Rafi Prasetyo",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "2014-11-05",
    kondisi_kesehatan: "Sakit",
    domisili_sekarang: "Medan",
  },
  {
    id: 11,
    account_id: 5,
    family_name: "Wati Prasetyo",
    family_hubungan: "Istri",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "1994-04-15",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Makassar",
  },
  {
    id: 12,
    account_id: 6,
    family_name: "Budi Handayani",
    family_hubungan: "Suami",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "1987-09-08",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Jakarta Utara",
  },
  {
    id: 13,
    account_id: 6,
    family_name: "Sinta Handayani",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "2016-02-14",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Jakarta Utara",
  },
  {
    id: 14,
    account_id: 7,
    family_name: "Lisa Gunawan",
    family_hubungan: "Istri",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "1988-12-03",
    kondisi_kesehatan: "Sakit",
    domisili_sekarang: "Bandung",
  },
  {
    id: 15,
    account_id: 7,
    family_name: "Kevin Gunawan",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "2013-08-17",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Bandung",
  },
  {
    id: 16,
    account_id: 8,
    family_name: "Doni Sari",
    family_hubungan: "Suami",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "1989-05-25",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Surabaya",
  },
  {
    id: 17,
    account_id: 9,
    family_name: "Mega Widodo",
    family_hubungan: "Istri",
    family_jenis_kelamin: "Perempuan",
    family_tanggal_lahir: "1986-07-11",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Medan",
  },
  {
    id: 18,
    account_id: 9,
    family_name: "Gibran Widodo",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "2009-10-28",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Medan",
  },
  {
    id: 19,
    account_id: 9,
    family_name: "Kaesang Widodo",
    family_hubungan: "Anak",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "2012-01-19",
    kondisi_kesehatan: "Sakit",
    domisili_sekarang: "Medan",
  },
  {
    id: 20,
    account_id: 10,
    family_name: "Andi Dewi",
    family_hubungan: "Suami",
    family_jenis_kelamin: "Laki-laki",
    family_tanggal_lahir: "1991-03-07",
    kondisi_kesehatan: "Sehat",
    domisili_sekarang: "Makassar",
  },
]

// Education Data
export const educations = [
  {
    id: 1,
    account_id: 1,
    education_tingkat: "S2",
    education_institusi: "Universitas Indonesia",
    education_jurusan: "Akuntansi",
    education_tahun_lulus: "2010",
    education_ipk: "3.75",
  },
  {
    id: 2,
    account_id: 2,
    education_tingkat: "S1",
    education_institusi: "Institut Teknologi Bandung",
    education_jurusan: "Manajemen",
    education_tahun_lulus: "2011",
    education_ipk: "3.68",
  },
  {
    id: 3,
    account_id: 3,
    education_tingkat: "S1",
    education_institusi: "Universitas Gadjah Mada",
    education_jurusan: "Ekonomi",
    education_tahun_lulus: "2013",
    education_ipk: "3.52",
  },
  {
    id: 4,
    account_id: 4,
    education_tingkat: "S2",
    education_institusi: "Universitas Airlangga",
    education_jurusan: "Akuntansi",
    education_tahun_lulus: "2012",
    education_ipk: "3.81",
  },
  {
    id: 5,
    account_id: 5,
    education_tingkat: "S1",
    education_institusi: "Universitas Hasanuddin",
    education_jurusan: "Administrasi Publik",
    education_tahun_lulus: "2015",
    education_ipk: "3.45",
  },
  {
    id: 6,
    account_id: 6,
    education_tingkat: "S2",
    education_institusi: "Universitas Indonesia",
    education_jurusan: "Manajemen Keuangan",
    education_tahun_lulus: "2014",
    education_ipk: "3.72",
  },
  {
    id: 7,
    account_id: 7,
    education_tingkat: "S1",
    education_institusi: "Institut Teknologi Bandung",
    education_jurusan: "Teknik Industri",
    education_tahun_lulus: "2009",
    education_ipk: "3.65",
  },
  {
    id: 8,
    account_id: 8,
    education_tingkat: "S1",
    education_institusi: "Universitas Brawijaya",
    education_jurusan: "Hukum",
    education_tahun_lulus: "2014",
    education_ipk: "3.58",
  },
  {
    id: 9,
    account_id: 9,
    education_tingkat: "S3",
    education_institusi: "Universitas Indonesia",
    education_jurusan: "Ilmu Administrasi",
    education_tahun_lulus: "2015",
    education_ipk: "3.89",
  },
  {
    id: 10,
    account_id: 10,
    education_tingkat: "S1",
    education_institusi: "Universitas Hasanuddin",
    education_jurusan: "Akuntansi",
    education_tahun_lulus: "2016",
    education_ipk: "3.41",
  },
]

// Training Data
export const trainings = [
  {
    id: 1,
    account_id: 1,
    training_nama: "Audit Keuangan Negara",
    training_penyelenggara: "BPKP",
    training_durasi: 40,
    training_tahun: "2020",
    training_sertifikat: true,
  },
  {
    id: 2,
    account_id: 2,
    training_nama: "Manajemen Risiko",
    training_penyelenggara: "LAN",
    training_durasi: 32,
    training_tahun: "2021",
    training_sertifikat: true,
  },
  {
    id: 3,
    account_id: 3,
    training_nama: "Sistem Pengendalian Internal",
    training_penyelenggara: "BPKP",
    training_durasi: 24,
    training_tahun: "2022",
    training_sertifikat: false,
  },
  {
    id: 4,
    account_id: 4,
    training_nama: "Audit Investigatif",
    training_penyelenggara: "KPK",
    training_durasi: 48,
    training_tahun: "2021",
    training_sertifikat: true,
  },
  {
    id: 5,
    account_id: 5,
    training_nama: "Tata Kelola Pemerintahan",
    training_penyelenggara: "LAN",
    training_durasi: 36,
    training_tahun: "2023",
    training_sertifikat: true,
  },
]

// Certification Data
export const certifications = [
  {
    id: 1,
    account_id: 1,
    certification_nama: "Certified Internal Auditor (CIA)",
    certification_penerbit: "IIA",
    certification_tanggal_terbit: "2019-06-15",
    certification_tanggal_berakhir: "2025-06-15",
  },
  {
    id: 2,
    account_id: 2,
    certification_nama: "Certified Public Accountant (CPA)",
    certification_penerbit: "AICPA",
    certification_tanggal_terbit: "2020-03-20",
    certification_tanggal_berakhir: "2026-03-20",
  },
  {
    id: 3,
    account_id: 4,
    certification_nama: "Certified Fraud Examiner (CFE)",
    certification_penerbit: "ACFE",
    certification_tanggal_terbit: "2021-09-10",
    certification_tanggal_berakhir: "2024-09-10",
  },
  {
    id: 4,
    account_id: 6,
    certification_nama: "Certified Management Accountant (CMA)",
    certification_penerbit: "IMA",
    certification_tanggal_terbit: "2022-01-25",
    certification_tanggal_berakhir: "2027-01-25",
  },
  {
    id: 5,
    account_id: 9,
    certification_nama: "Certified Government Auditing Professional (CGAP)",
    certification_penerbit: "IIA",
    certification_tanggal_terbit: "2018-11-30",
    certification_tanggal_berakhir: "2024-11-30",
  },
]

// Position Data
export const positions = [
  {
    id: 1,
    account_id: 1,
    position_jabatan: "Auditor Ahli Utama",
    position_unit: "Inspektorat Utama",
    position_tanggal_mulai: "2020-01-01",
    position_tanggal_selesai: null,
  },
  {
    id: 2,
    account_id: 1,
    position_jabatan: "Auditor Ahli Madya",
    position_unit: "Inspektorat Utama",
    position_tanggal_mulai: "2017-06-01",
    position_tanggal_selesai: "2019-12-31",
  },
  {
    id: 3,
    account_id: 2,
    position_jabatan: "Auditor Ahli Madya",
    position_unit: "Inspektorat Wilayah I",
    position_tanggal_mulai: "2019-03-01",
    position_tanggal_selesai: null,
  },
  {
    id: 4,
    account_id: 3,
    position_jabatan: "Auditor Ahli Muda",
    position_unit: "Inspektorat Wilayah II",
    position_tanggal_mulai: "2021-07-01",
    position_tanggal_selesai: null,
  },
  {
    id: 5,
    account_id: 4,
    position_jabatan: "Auditor Ahli Pertama",
    position_unit: "Inspektorat Wilayah III",
    position_tanggal_mulai: "2018-09-01",
    position_tanggal_selesai: null,
  },
]

// Placement History Data
export const placementHistories = [
  {
    id: 1,
    name: "Ahmad Wijaya",
    location: "Jakarta",
    start: "2020-01-01",
    to: null,
  },
  {
    id: 2,
    name: "Siti Nurhaliza",
    location: "Bandung",
    start: "2019-03-01",
    to: null,
  },
  {
    id: 3,
    name: "Budi Santoso",
    location: "Surabaya",
    start: "2021-07-01",
    to: null,
  },
  {
    id: 4,
    name: "Dewi Sartika",
    location: "Medan",
    start: "2018-09-01",
    to: null,
  },
  {
    id: 5,
    name: "Eko Prasetyo",
    location: "Makassar",
    start: "2022-02-01",
    to: null,
  },
]

// Assistance History Data
export const assistanceHistories = [
  {
    id: 1,
    name: "Ahmad Wijaya",
    unit: "Inspektorat Utama",
    location: "Jakarta",
    task: "Audit LKPD",
    start: "2023-01-15",
    to: "2023-03-15",
  },
  {
    id: 2,
    name: "Siti Nurhaliza",
    unit: "Inspektorat Wilayah I",
    location: "Bandung",
    task: "Audit Kinerja",
    start: "2023-02-01",
    to: null,
  },
  {
    id: 3,
    name: "Budi Santoso",
    unit: "Inspektorat Wilayah II",
    location: "Surabaya",
    task: "Audit Investigatif",
    start: "2023-03-10",
    to: "2023-05-10",
  },
  {
    id: 4,
    name: "Dewi Sartika",
    unit: "Inspektorat Wilayah III",
    location: "Medan",
    task: "Audit Khusus",
    start: "2023-04-01",
    to: null,
  },
  {
    id: 5,
    name: "Eko Prasetyo",
    unit: "Inspektorat Wilayah IV",
    location: "Makassar",
    task: "Audit Tindak Lanjut",
    start: "2023-05-15",
    to: "2023-07-15",
  },
]

// Audit Assignment Data
export const auditAssignments = [
  {
    id: 1,
    name: "Ahmad Wijaya",
    location: "Jakarta",
    classify: "lkpd",
    entity: "Pemerintah Provinsi DKI Jakarta",
    role: "ketua",
    area: "Pendapatan Asli Daerah",
    indicator_of_area: "Penerimaan pajak daerah tidak optimal",
    start: "2023-01",
    to: "2023-03",
  },
  {
    id: 2,
    name: "Siti Nurhaliza",
    location: "Bandung",
    classify: "kinerja",
    entity: "Dinas Pendidikan Provinsi Jawa Barat",
    role: "anggota",
    area: "Program Pendidikan",
    indicator_of_area: "Capaian target pendidikan rendah",
    start: "2023-02",
    to: null,
  },
  {
    id: 3,
    name: "Budi Santoso",
    location: "Surabaya",
    classify: "investigatif",
    entity: "RSUD Dr. Soetomo",
    role: "ketua",
    area: "Pengadaan Barang dan Jasa",
    indicator_of_area: "Indikasi markup harga",
    start: "2023-03",
    to: "2023-05",
  },
  {
    id: 4,
    name: "Dewi Sartika",
    location: "Medan",
    classify: "khusus",
    entity: "PT. Perkebunan Nusantara IV",
    role: "anggota",
    area: "Manajemen Keuangan",
    indicator_of_area: "Kerugian operasional tinggi",
    start: "2023-04",
    to: null,
  },
  {
    id: 5,
    name: "Eko Prasetyo",
    location: "Makassar",
    classify: "tindak_lanjut",
    entity: "Pemerintah Kota Makassar",
    role: "ketua",
    area: "Infrastruktur",
    indicator_of_area: "Rekomendasi belum ditindaklanjuti",
    start: "2023-05",
    to: "2023-07",
  },
]
